# roles/k3s/tasks/main.yml
- name: Install K3s
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Wait for node ready
  shell: kubectl get nodes
  register: result
  retries: 10
  delay: 10
  until: result.rc == 0